theme: jekyll-theme-cayman
title: Saumik Bhattacharya
description : The more I read, the more I acquire, the more certain I am that I know nothing
#site.github.is_project_page: false
github:
  is_project_page: false
